### ISSUE TITLE
Selecting text with Shift+Arrows is slow

### ISSUE THREAD

**Issue by jakubmisek** [balupton/mercury#23]
When I'm selecting text by holding Shift and pressing arrow keys, Chrome process consumes the whole CPU core.

On some parts of the text it is ok :-/ Also deletion/pasting of large selection (about 500 words) takes some time (about 1sec or more on Core i7 3.7GHz ...)

**Comment by balupton** [comment]
https://github.com/balupton/mercury/issues/27
